### ISSUE TITLE
Replace slide deck through website

### ISSUE THREAD

**Issue by martinweck** [innoq/SCS#58]
If we have slides, we may run into issues:

- how do you keep them consistent on the website? e.g., slides say we have to use ROCA, which is not the case on the website
- someone downloads the slides and uses them instead of the website. The website is updated, but the slides are not.
- how do you handle versioning of the slides?
- is it accessible for e.g. blind persons?
- the slide deck is available in keynote, pptx, why not in a standardized format like ISO 26300
- the slide deck is available in English, German, why not in other languages? (websites can be translated via browser plug-ins)

Suggestion for acceptance criteria:
- There exists a What? website that contains:
  - definition of SCS
  - characteristics of SCS
  - all information with images taken from the slides
- The What? page replaces the current index/home page.
- The download links and embedded slide deck have been removed

This issue eases solving https://github.com/innoq/SCS/issues/48.

**Comment by felixbutton** [comment]
I second this. All information should be available and linkable directly from the website. A relevant slide deck from a conference talk could still be featured within the "links" section if neccessary (in this case it would also have more context to it).

**Comment by hollesse** [comment]
One idea I had is if we should replace the presentation with a handout of maybe even an SCS Primer. The primer would be a great idea for conferences but for the website maybe a short handout which is nicely designed would be cool. Maybe in the format of sketch notes or something like that. Just an idea that came to my mind.

**Comment by mvitz** [comment]
This repository, although living within the INNOQ GitHub organization, contains the open-sourced and unbranded SCS concept. I doubt that this is the right place to discuss marketing specific stuff like handouts or primers.

**Comment by hollesse** [comment]
I stated it here as it could be a replacement for the slides.

**Comment by martinweck** [comment]
well, we have the slides now on the site and download links as requested by @youngbrioche . So there is everything for everyone. Hence, I close this ticket now. If you disagree, feel free to re-open the ticket/create a new ticket.
