### ISSUE TITLE
Unclear if SCS without UI is allowed

### ISSUE THREAD

**Issue by bragern** [innoq/SCS#89]
We're in the middle of a discussion if a SCS mandatorily has to contain a UI or if it is possible to have a self contained system that does not offer it's functionality to a human user. 

What the spec says;
> An SCS should make its features usable to end-users via its own UI.

=> 'should' does not mean 'has to'

> An SCS contains its own user interface, specific business logic and separate data storage .

=> Primarily means to me 'Does not share any of these with others' but does it necessarily also mean 'Needs to have all of these'?

An example would be a system to collect and process some data and only pass this on via a machine readable interface for another SCS to consume via a service API (which an SCS is allowed to have). Would you rather call this a (micro)-service accompanying your SCS or would you consider this an SCS without UI?

**Comment by ewolff** [comment]
An SCS has to have its own UI. That is the core of the idea. Thanks for bringing this up, it has to be clarified. 🙂

**Comment by bragern** [comment]
Thanks for this very quick answer. 

So this means, I might have 1-n SCS's in my landscape accompanied by 1-m non-SCS services?

What would you call such a service then? Just a service?

**Comment by ewolff** [comment]
There might be other types of architectures in an IT landscape, correct. What you might call them is beyond the definition of SCS, I am afraid.

**Comment by vanto** [comment]
>So this means, I might have 1-n SCS's in my landscape accompanied by 1-m non-SCS services?
>What would you call such a service then? Just a service?

In addition to @ewolff's reply, an SCS might be realized as a bunch of microservices, as long it as at least one endpoint provides a UI. If your non-ui service is within the boundary of the same business domain and somewhat belongs to the problem the SCS is expected to solve, it would be fine to just consider this service an implementation detail of the SCS.

**Comment by mechanoid** [comment]
We had a similar discussion in the past about systems that solely serve external clients like mobile applications or IoT devices, and if such system can still be named SCS. The gist of that discussion was, as far as I remember, that while such systems can adhere to many of the principals it is not strictly the same. But nonetheless I think that it is a good idea to aim for the same strategies, when you share a lot of the goals that SCS have.
